# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kaspterio from meituan
email: zhangheng21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi~ I am a software engineer from Meituan. Now, the most commonly used programming language in my work is PHP and Java, and I'm  also familiar with C and Python. By the way, I'm pretty fascinated with UNIX system, and I love to write small utils and scripts on that. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kapsterio.com" # the base hostname & protocol for your site
twitter_username: null
github_username:  kapsterio

# Build settings
markdown: kramdown
